# Generated by Django 3.1 on 2020-12-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_App', '0004_auto_20201207_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
