# Generated by Django 3.1 on 2020-12-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_App', '0005_auto_20201207_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='number',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
