# Generated by Django 3.1 on 2020-12-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_App', '0007_auto_20201207_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission',
            name='number',
            field=models.IntegerField(),
        ),
    ]
